name: Download Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Video page URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install yt-dlp + ffmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg
        pip install yt-dlp

    - name: Create folder
      run: mkdir -p video

    - name: Download video
      run: |
        URL="${{ github.event.inputs.url }}"

        yt-dlp \
          --retries 10 \
          --fragment-retries 10 \
          --merge-output-format mp4 \
          -o "video/%(title)s.%(ext)s" \
          "$URL"

    - name: Split if bigger than 95MB
      run: |
        cd video
        FILE=$(ls | head -n 1)

        SIZE=$(stat -c%s "$FILE")

        if [ "$SIZE" -gt 95000000 ]; then
          echo "File too big, splitting..."
          split -b 90M "$FILE" "$FILE.part."
          rm "$FILE"
        fi

    - name: Commit files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add video/*
        git commit -m "Add downloaded video" || echo "Nothing to commit"
        git push
